# Dependencies
markdown:         kramdown
highlighter:         pygments
excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

# Setup
title:            1Few
tagline:          '每天进步一点点'
description:      'One of a few people likes one of a few things.'
url:              http://www.1few.com
baseurl:          /

author:
  name:           'syler'
  url:            https://twitter.com/sylerz

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

JB:
  tags_path: /tags

  comments:
    provider: disqus
    disqus:
      short_name: sylerz
  analytics:
    provider: yandex
    google:
      tracking_id: UA-54509421-1
